# Site settings
title: Learn Python!
email: marwahaha@berkeley.edu
description: New to programming? Check out Learn Python, a D-Lab Working Group.
# > # this means to ignore newlines until "baseurl:"
#   Write an awesome description for your new site here. You can edit this
#   line in _config.yml. It will appear in your document head meta (for
#   Google search results) and in your feed.xml site description.

gems:
  - jekyll-redirect-from

#Show future posts!
future: true



# README README comment the below line out for local stuff!
baseurl: "http://python.berkeley.edu" # the subpath of your site, e.g. /blog/




# url: "http://yourdomain.com" # the base hostname & protocol for your site
# twitter_username: jekyllrb
github_username: marwahaha
permalink: /:year-:month-:day-:title/
# this is the url root of the view source link on the footer page.
viewsourceroot: https://github.com/dlab-berkeley/python-berkeley/blob/gh-pages/
# this is the url root of the create page link on the footer page.
newsourceroot: https://github.com/dlab-berkeley/python-berkeley/blob/gh-pages/
#########################################
# for duoshuo.com commenting system, uncomment following line if you do not want to include duoshuo.com. 
#duoshuo_shortname: lixizhi
#duoshuo_url: "http://lixizhi.github.io"
# disqus.com commenting system. please note that it is exclusive with duoshuo.com
#disqus_shortname: lixizhi
#disqus_url: "http://lixizhi.github.io"
#########################################

# Build settings
markdown: kramdown

kramdown:
    smartquotes: ["apos", "apos", "quot", "quot"]
    smart_quotes: ["apos", "apos", "quot", "quot"]


# highlight
# highlighter: pygments
# highlighter: rouge
# highlighter: false
