# Site settings
title: Python Practice
email: mcarey@berkeley.edu
description: >
    New to programming? Here is a collection of learning resources for the
    Python programming language and information about projects that use it on
    the UC Berkeley campus.
gems:
  - jekyll-redirect-from
future: true #so you see future posts!
github_username: dlab-berkeley/python-berkeley #for github link in footer
permalink: /:year-:month-:day-:title/
viewsourceroot: https://github.com/dlab-berkeley/python-berkeley/edit/gh-pages/ #link in footer to edit this page




############################################
##      NOT SURE ABOUT THESE SETTINGS     ##

############################################
newsourceroot: https://github.com/dlab-berkeley/python-berkeley/blob/gh-pages/
############################################
# url: "http://yourdomain.com" # the base hostname & protocol for your site
# twitter_username: jekyllrb
############################################
# for duoshuo.com commenting system, uncomment following line if you do not want to include duoshuo.com. 
#duoshuo_shortname: lixizhi
#duoshuo_url: "http://lixizhi.github.io"
# disqus.com commenting system. please note that it is exclusive with duoshuo.com
#disqus_shortname: lixizhi
#disqus_url: "http://lixizhi.github.io"
#########################################
# Build settings
# This is default
markdown: kramdown
kramdown:
     smart_quotes: ["apos", "apos", "quot", "quot"] #smart quotes do stupid things with this theme, so turns them off
# The default highlighter for Jekyll, and the ONLY one on GitHub
# highlighter: rouge
