# Site settings
title: Learn Python!
email: marwahaha@berkeley.edu
description: New to programming? Here is a collection of learning resources for the Python programming language and information about projects that use it on the UC Berkeley campus.
# > # this means to ignore newlines until "baseurl:"
#   Write an awesome description for your new site here. You can edit this
#   line in _config.yml. It will appear in your document head meta (for
#   Google search results) and in your feed.xml site description.

gems:
  - jekyll-redirect-from

#Show future posts!
future: true


# You never need this, even when the site is live on GitHub -DJC
# README README comment the below line out for local stuff!
# baseurl: "http://python.berkeley.edu" # the subpath of your site, e.g. /blog/




# url: "http://yourdomain.com" # the base hostname & protocol for your site
# twitter_username: jekyllrb
#github_username controls the github link at the bottom of the page.
github_username: dlab-berkeley/python-berkeley
permalink: /:year-:month-:day-:title/

# this is the url root of the view source link on the footer page.
# UPDATE: now it's an edit link
viewsourceroot: https://github.com/dlab-berkeley/python-berkeley/edit/gh-pages/
# this is the url root of the create page link on the footer page.
# UPDATE: this is now unused
newsourceroot: https://github.com/dlab-berkeley/python-berkeley/blob/gh-pages/
#########################################
# for duoshuo.com commenting system, uncomment following line if you do not want to include duoshuo.com. 
#duoshuo_shortname: lixizhi
#duoshuo_url: "http://lixizhi.github.io"
# disqus.com commenting system. please note that it is exclusive with duoshuo.com
#disqus_shortname: lixizhi
#disqus_url: "http://lixizhi.github.io"
#########################################

# Build settings
markdown: kramdown

# XXX - This is clearly in need of attention...
kramdown:
    smart_quotes: ["apos", "apos", "quot", "quot"]


# highlight
# highlighter: pygments
# highlighter: rouge
# highlighter: false
